version: '3'
services:
  jenkins:
    container_name: jenkins
    build: ./
    image: jenkins-docker
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
    jenkins_home:
